Flaunt-Digital/orange-shopify-theme

sections/image-text-stack.liquid

Just updated the filter to get the images to load on staging

updated image filter ( now works )

---

assets/spacer-block.css
sections/spacer-block.liquid

Spacer block

---

assets/section-key-features.css
sections/key-features.liquid

Key features block

---

assets/component-product-card.css

fixed rich text block

---

assets/section-image-text-stack.css
sections/image-text-stack.liquid
src/gsap.js

responsive design and renaming classes

---

sections/highlight-text.liquid

Highlight text responsive and padding settings

---

sections/image-text-stack.liquid

Add padding settings and colour scheme settings

---

assets/component-product-card.css
assets/section-tabbed-products.css
assets/tabbed-products.js
sections/tabbed-products.liquid
snippets/product-card-tabbed-products.liquid

Best sellers block - added padding, colour schema, responsive design, renamed classes

---

sections/usp-block.liquid

removed usp-3 render

---

assets/gallery-with-thumbs.css
sections/gallery-with-thumbs.liquid

gallery with thumbnails

---

sections/quote-carousel.liquid

update to include shopify settings

---

templates/product.json

removed key features

---

assets/component-mega-menu.css

nav draw hotfix

---

assets/campaign-block.css
sections/campaign-block.liquid

campaign block

---

assets/campaign-block.css
assets/gallery-with-thumbs.css
assets/scrollable-artists.css
sections/awards-carousel.liquid
sections/campaign-block.liquid
sections/gallery-with-thumbs.liquid
sections/image-text-stack.liquid
sections/scrollable-artists.liquid

Multiple block updates

---

assets/quote-carousel.css
sections/quote-carousel.liquid

quote block fix

---

assets/section-introductory-text.css
sections/introductory-text.liquid

added introductory text block

---

assets/campaign-block.css
assets/flicker-slider.css
assets/flicker-slider.js
assets/product-innovation.css
sections/flicker-slider.liquid

flicker block

---

assets/flicker-slider.css
assets/product-innovation.css
sections/product-innovation.liquid

Product inno block

---

assets/section-highlight-text.css
sections/highlight-text.liquid

text scroll update
